// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf.proto

package gosercomp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtoColorGroup struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name                 *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Colors               []string `protobuf:"bytes,3,rep,name=colors" json:"colors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoColorGroup) Reset()         { *m = ProtoColorGroup{} }
func (m *ProtoColorGroup) String() string { return proto.CompactTextString(m) }
func (*ProtoColorGroup) ProtoMessage()    {}
func (*ProtoColorGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobuf_c84a1743fed88ba5, []int{0}
}
func (m *ProtoColorGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoColorGroup.Unmarshal(m, b)
}
func (m *ProtoColorGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoColorGroup.Marshal(b, m, deterministic)
}
func (dst *ProtoColorGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoColorGroup.Merge(dst, src)
}
func (m *ProtoColorGroup) XXX_Size() int {
	return xxx_messageInfo_ProtoColorGroup.Size(m)
}
func (m *ProtoColorGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoColorGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoColorGroup proto.InternalMessageInfo

func (m *ProtoColorGroup) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProtoColorGroup) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ProtoColorGroup) GetColors() []string {
	if m != nil {
		return m.Colors
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoColorGroup)(nil), "gosercomp.ProtoColorGroup")
}

func init() { proto.RegisterFile("protobuf.proto", fileDescriptor_protobuf_c84a1743fed88ba5) }

var fileDescriptor_protobuf_c84a1743fed88ba5 = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x03, 0x33, 0x84, 0x38, 0xd3, 0xf3, 0x8b, 0x53, 0x8b, 0x92, 0xf3,
	0x73, 0x0b, 0x94, 0x7c, 0xb9, 0xf8, 0x03, 0x40, 0x62, 0xce, 0xf9, 0x39, 0xf9, 0x45, 0xee, 0x45,
	0xf9, 0xa5, 0x05, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0xac, 0x41,
	0x4c, 0x99, 0x29, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a, 0x4c, 0x1a,
	0x9c, 0x41, 0x60, 0xb6, 0x90, 0x18, 0x17, 0x5b, 0x32, 0x48, 0x47, 0xb1, 0x04, 0xb3, 0x02, 0xb3,
	0x06, 0x67, 0x10, 0x94, 0x07, 0x08, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x06, 0x8c, 0xd5, 0x6a, 0x00,
	0x00, 0x00,
}
